Document: acpi-mpd
Title: Debian acpi-mpd Manual
Author: <insert document author here>
Abstract: This manual describes what acpi-mpd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acpi-mpd/acpi-mpd.sgml.gz

Format: postscript
Files: /usr/share/doc/acpi-mpd/acpi-mpd.ps.gz

Format: text
Files: /usr/share/doc/acpi-mpd/acpi-mpd.text.gz

Format: HTML
Index: /usr/share/doc/acpi-mpd/html/index.html
Files: /usr/share/doc/acpi-mpd/html/*.html
